# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-04-09 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(default=178, verbose_name='身高')),
                ('age', models.IntegerField(default=22, verbose_name='本人年龄')),
                ('describe', models.CharField(default='这个人很懒...什么都没有留下！！！', max_length=128, verbose_name='个人签名')),
                ('married', models.CharField(default='未婚', max_length=8, verbose_name='婚姻状况')),
                ('edu', models.CharField(default='博士', max_length=15, verbose_name='学历')),
                ('occu', models.CharField(default='保密', max_length=36, verbose_name='职业')),
                ('figure', models.CharField(default='高挑型', max_length=12, verbose_name='体重')),
                ('weight', models.IntegerField(default=45, verbose_name='身材')),
                ('qq', models.IntegerField(default=1406159466, verbose_name='QQ')),
                ('dating_gender', models.CharField(choices=[('male', '男性'), ('female', '女性')], default='male', max_length=6, verbose_name='匹配的性别')),
                ('dating_location', models.CharField(choices=[('北京', '北京'), ('上海', '上海'), ('深圳', '深圳'), ('郑州', '郑州'), ('西安', '西安'), ('成都', '成都'), ('沈阳', '沈阳'), ('安阳', '安阳'), ('福州', '福州'), ('宁德', '宁德')], default='上海', max_length=15, verbose_name='目标城市')),
                ('min_distance', models.IntegerField(default=1, verbose_name='最小查找范围')),
                ('max_distance', models.IntegerField(default=10, verbose_name='最大查找范围')),
                ('min_dating_age', models.IntegerField(default=18, verbose_name='最小交友年龄')),
                ('max_dating_age', models.IntegerField(default=50, verbose_name='最大交友年龄')),
                ('vibration', models.BooleanField(default=True, verbose_name='是否开启震动')),
                ('only_matche', models.BooleanField(default=True, verbose_name='不让未匹配的人看我的相册')),
                ('auto_play', models.BooleanField(default=True, verbose_name='自动播放视频')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenum', models.CharField(max_length=15, unique=True, verbose_name='手机号')),
                ('nickname', models.CharField(default='匿名用户', max_length=20, verbose_name='昵称')),
                ('gender', models.CharField(choices=[('male', '男性'), ('female', '女性')], default='male', max_length=6, verbose_name='性别')),
                ('birthday', models.DateField(default='1990-01-01', verbose_name='生日')),
                ('location', models.CharField(choices=[('北京', '北京'), ('上海', '上海'), ('深圳', '深圳'), ('郑州', '郑州'), ('西安', '西安'), ('成都', '成都'), ('沈阳', '沈阳'), ('安阳', '安阳'), ('福州', '福州'), ('宁德', '宁德')], default='上海', max_length=15, verbose_name='常居地')),
                ('avatar', models.CharField(max_length=256, verbose_name='个人形象')),
                ('vip_id', models.IntegerField(default=1, verbose_name='用户对应的会员 ID')),
                ('vip_end', models.DateTimeField(default='3000-1-1', verbose_name='会员过期时间')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
